framework:
    mailer:
        dsn: 'smtp://constantkilayossi@gmail.com:dvmcagynrseciexs@smtp.gmail.com:587?encryption=tls&auth_mode=login'
        envelope:
            sender: 'constantkilayossi@gmail.com'
